services:
  cowrie:
    image: cowrie/cowrie
    container_name: cowrie
    ports:
      - "2222:2222"
    volumes:
      - ./honeypots/cowrie/cowrie.cfg:/cowrie/cowrie.cfg
      - ./data/logs/cowrie:/cowrie/var/log/cowrie
    restart: unless-stopped

  dionaea:
    image: honeynet/dionaea
    container_name: dionaea
    network_mode: host 
    volumes:
      - ./data/logs/dionaea:/opt/dionaea/var/dionaea
    restart: unless-stopped

  flask-fake-login:
    build:
      context: ./honeypots/flask-fake-login
    container_name: flask-fake-login
    ports:
      - "5000:5000"
    volumes:
      - ./data/logs/flask-fake-login:/app
    restart: unless-stopped
