version: '3.8'

services:
  cowrie:
    image: cowrie/cowrie
    container_name: cowrie
    ports:
      - "2222:2222"
    volumes:
      - ./honeypots/cowrie/cowrie.cfg:/cowrie/etc/cowrie.cfg
      - ./data/logs/cowrie:/cowrie/var/log/cowrie
    restart: unless-stopped
    
  dionaea:
    image: dinotools/dionaea
    container_name: dionaea
    ports:
      - "21:21"
      - "23:23"
      - "80:80"
      - "135:135"
      - "443:443"
      - "445:445"
    volumes:
      - ./data/logs/dionaea:/opt/dionaea/var/dionaea
    restart: unless-stopped
    
  flask-fake-login:
    build:
      context: ./honeypots/flask-fake-login
    container_name: flask-fake-login
    ports:
      - "5000:5000"
    volumes:
      - ./data/logs/flask-fake-login:/app/logs
    restart: unless-stopped