version: '3.8'

services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie-honeypot
    ports:
      - "2222:2222/tcp"
    volumes:
      - ./config/cowrie-config/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg:ro
      - ./data/logs/cowrie:/cowrie/cowrie-git/var/log/cowrie
      - cowrie-data:/cowrie/cowrie-git/var/lib/cowrie
    restart: unless-stopped
    environment:
      - COWRIE_UID=1000
      - COWRIE_GID=1000

  dionaea:
    image: dinotools/dionaea:latest
    container_name: dionaea-honeypot
    ports:
      - "21:21"     # FTP
      - "23:23"     # Telnet  
      - "8080:80"   # HTTP
      - "8443:443"  # HTTPS
      - "1135:135"  # SMB
      - "8445:445"  # SMB
    volumes:
      - ./data/logs/dionaea:/opt/dionaea/var/log/dionaea
      - ./data/dionaea:/opt/dionaea/var/lib/dionaea
    restart: unless-stopped

  flask-fake-login:
    build:
      context: ./honeypots/flask-fake-login
    container_name: flask-fake-login
    ports:
      - "5000:5000"
    volumes:
      - ./data/logs/flask-fake-login:/app/logs
    restart: unless-stopped
    environment:
      - FLASK_ENV=production

volumes:
  cowrie-data: